AddCSLuaFile()

ENT.Base 			= "looting_storage_base"
ENT.PrintName		= "Мусор в городе 1"
ENT.Category        = "Мусор"
ENT.Spawnable		= true

ENT.lootModel = "models/props_junk/cardboard_box003a.mdl"
ENT.lootPos = { forward = 0, up = 25, right = 0 }
ENT.timeToLoot = 10
ENT.cooldownTime = 420

ENT.lootList = {}
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList[""] = 25
ENT.lootList["weapon_hl2axe"] = 1
ENT.lootList["weapon_hl2axe"] = 1
ENT.lootList["weapon_hl2axe"] = 1
ENT.lootList["weapon_hl2axe"] = 1
ENT.lootList["weapon_hl2axe"] = 1
ENT.lootList["vzlom_polya"] = 1
ENT.lootList["vzlom_polya"] = 1
ENT.lootList["vzlom_polya"] = 1
ENT.lootList["vzlom_polya"] = 1
ENT.lootList["vzlom_polya"] = 1
ENT.lootList["rp_water"] = 1
ENT.lootList["rp_water"] = 1
ENT.lootList["rp_water"] = 1
ENT.lootList["rp_water"] = 1
ENT.lootList["rp_water"] = 1
ENT.lootList["lockpick"] = 1
ENT.lootList["lockpick"] = 1
ENT.lootList["lockpick"] = 1
ENT.lootList["lockpick"] = 1
ENT.lootList["lockpick"] = 1